[cellBlocks]
shellProfiles = "/shellProfiles" #toml,nix
shell = "/shell" # nix
tasks = "/tasks"
configs = "/configs" #json,toml,yaml
schemas = "/schemas" #json,toml,yaml

[devshell]
# programs.sops.enable = true;
# programs.age.enable = true;
# programs.k8s..enabel = true;
# [[programs.terraform]]
#  enable = true,
#  plugins = ["aws"],
