[cellsFrom]
devshell = "/devshell"
tasks = "/tasks"

[devshell]
# programs.sops.enable = true;
# programs.age.enable = true;
# [[programs.terraform]]
#  enable = true,
#  plugins = ["aws"],
packages = [
  "d2"
]
