[cellsFrom]
devshell = "/cells/devshell"
tasks = "/cells/tasks"
schemas = "/tenzir/schemas"

[devshell]
# programs.sops.enable = true;
# programs.age.enable = true;
# programs.k8s..enabel = true;
# [[programs.terraform]]
#  enable = true,
#  plugins = ["aws"],
packages = ["d2", "hello"]
