[cellsFrom]
devshell = "/devshell"
tasks = "/tasks"
configs = "/configs"
schemas = "/tenzir/schemas"

[devshell]
# programs.sops.enable = true;
# programs.age.enable = true;
# programs.k8s..enabel = true;
# [[programs.terraform]]
#  enable = true,
#  plugins = ["aws"],
