name: "OCI"
on:
  push:
    branches: [main]
  pull_request:

jobs:
  nix-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: nixbuild/nix-quick-install-action@v25
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: copy oci-image to the register
        run: |
          nix run ./#x86_64-linux.dev.containers.default.out.copyToRegistry
